### PR TITLE
localdb integration and minor fixes

### LINKED ISSUE #35: integrate localdb instead of consumer cache

### PR DESCRIPTION
**Pull request by adam-thibodeaux**
fixes #35 

- localdb integrated with backend in the form of sqlite db
- deleted consumercache in memory store
- updated kafka to grab total offsets instead of number of messages consumed
- updated data gathering to use admin instead of consumer
- added 404 handler in server
- added routes for kafka
- added comments for clarity
- moved functionality from graph to the selector panel

### CODE REVIEW

File: client/server/kafkaController.ts [hunk 1]
```diff
@@ -1,63 +1,195 @@
 import * as express from 'express';
 import * as kafka from 'kafkajs';
+import sqlite3 from 'sqlite3';
+import { open } from 'sqlite';
 interface controller {
```
Comment (shamilahfaria) [inline client/server/kafkaController.ts:5]: create nested interfaces -- 
interface for express functions with (req, res, and next) predefined. 
perhaps in a file to import into any express file

**Review by shamilahfaria — APPROVED** [review]

**Review by kasthurimenon — APPROVED** [review]
Reviewed. Looks good, Adam! ;)
